name:                Latte
version:             0.9.1.0
github:              "githubuser/Latte"
license:             MIT
author:              "Mateusz Gienieczko"
maintainer:          "matgienieczko@gmail.com"
copyright:           "2020 Mateusz Gienieczko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/V0ldek/Latte#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5 && < 0.6
- mtl >= 2.2 && < 2.3
- containers >= 0.6 && < 0.7
- directory >= 1.3 && < 1.4
- filepath >= 1.4 && < 1.5
- process >= 1.6 && < 1.7
- hspec >= 2.7 && < 2.8
- regex >= 1.1 && < 1.2

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fno-warn-type-defaults

executables:
  latc_x86_64:
    main:                Latc_x86_64.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Latc_x86_64
    - -Wall
    dependencies:
    - Latte
  espi:
    main:                Espi.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Espi
    - -Wall
    dependencies:
    - Latte

tests:
  Latte-test:
    main:                Spec.hs
    source-dirs:         test/Discovery
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - Latte
  Latte-exec-test:
    main:                X86_64Spec.hs
    source-dirs:         test/Exec
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is X86_64Spec
    - -Wall
    dependencies:
    - Latte